apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-backend
  template:
    metadata:
      labels:
        app: juice-backend
    spec:
      containers:
        - name: backend
          image: risewithmedia/juice-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              value: "mongodb://mongo:27017/juice-erp"

---
apiVersion: v1
kind: Service
metadata:
  name: juice-backend
spec:
  selector:
    app: juice-backend
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-frontend
  template:
    metadata:
      labels:
        app: juice-frontend
    spec:
      containers:
        - name: frontend
          image: risewithmedia/juice-frontend:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: juice-frontend
spec:
  type: LoadBalancer
  selector:
    app: juice-frontend
  ports:
    - protocol: TCP
      port: 87
      targetPort: 80
